### PR TITLE
support msgpack 1.1.0

### LINKED ISSUE #3: importing from cmsgpack is not accepted by mypy even with msgpack-types installed
My project strongly relies on fast msgpack C extension
we check if it is available by importing from `msgpack._cmsgpack` (the same method is used inside msgpack to decide if use the fallback mode)
it would be nice if mypy was recognizing types from inside the _cmsgpack submodule when msgpack-types installed.

### PR DESCRIPTION
**Pull request by trim21**
inherit from `_ExtType(NamedTuple)` may cause some problem, also we are typing stubs, there is no need to inherit from `class T(NamedTuple)`.

and `TimeStamp` doesn't exists in msgpack 1.1.0, only `Timestamp`

also fix https://github.com/sbdchd/msgpack-types/issues/3

### CODE REVIEW

**Comment by trim21** [comment]
also we should add msgpack version spec in deps list, so stubs can match impl if msgpack release a new version

**Review by sbdchd — APPROVED** [review]

**Comment by sbdchd** [comment]
Thank you!

**Comment by trim21** [comment]
new release？

**Comment by sbdchd** [comment]
done!

**Pull request merged**
